### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by flwh** [icymind/VRouter#35]
Error: Command failed: "C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" startvm --type headless vrouter
VBoxManage.exe: error: Nonexistent host networking interface, name 'undefined' (VERR_INTERNAL_ERROR)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by icymind** [comment]
没能获取物理网卡的名称, 能贴下在 cmd 下命令 `WMIC nic where "PhysicalAdapter = TRUE and NetConnectionStatus = 2" get InterfaceIndex,Name`的运行结果吗?

**Comment by flwh** [comment]
C:\Users\mapleflwh>WMIC nic where "PhysicalAdapter = TRUE and NetConnectionStatus = 2" get InterfaceIndex,Name
InterfaceIndex  Name
11              VMware Virtual Ethernet Adapter for VMnet1
8               VMware Virtual Ethernet Adapter for VMnet8
3               Xiaomi 802.11n USB Wireless Adapter
40              VirtualBox Host-Only Ethernet Adapter
48              VirtualBox Host-Only Ethernet Adapter #2

**Comment by icymind** [comment]
知道 bug 所在了, 麻烦再贴日志确认下, 谢谢.
位置在`%USERPROFILE%/AppData/Roaming/vrouter/vrouter.log`

**Comment by flwh** [comment]
2017-09-06T18:02:43+08:00 - info: building vm
2017-09-06T18:03:34+08:00 - info: no hostonlyifs with 10.19.28.46 available. create a new one then configure it
2017-09-06T18:04:04+08:00 - info: hostonlyInf: VirtualBox Host-Only Ethernet Adapter #2
2017-09-06T18:04:04+08:00 - info: bridgeServices: Xiaomi 802.11n USB Wireless Adapter,Realtek PCIe FE Family Controller,TAP-Windows Adapter V9
2017-09-06T18:04:06+08:00 - info: actived Bridge Service: undefined
2017-09-06T18:04:12+08:00 - error: build error: Error: Command failed: "C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" startvm --type headless vrouter
VBoxManage.exe: error: Nonexistent host networking interface, name 'undefined' (VERR_INTERNAL_ERROR)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

2017-09-06T18:04:33+08:00 - info: building vm
2017-09-06T18:04:33+08:00 - error: build error: Error: Command failed: "C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" createvm --name vrouter --register
VBoxManage.exe: error: Machine settings file 'C:\Users\mapleflwh\VirtualBox VMs\vrouter\vrouter.vbox' already exists
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "CreateMachine(bstrSettingsFile.raw(), bstrName.raw(), ComSafeArrayAsInParam(groups), bstrOsTypeId.raw(), createFlags.raw(), machine.asOutParam())" at line 273 of file VBoxManageMisc.cpp

**Comment by icymind** [comment]
已通过  https://github.com/icymind/VRouter/commit/e0f95d5809d65fce08011018014cc7938537a75d 修复.

请下载alpha-3版本, 删除构建失败的虚拟机然后重建一次
