### ISSUE TITLE
未能安装必要软件包；构建错误；Error: Cannot read property '1' of null

### ISSUE THREAD

**Issue by Maecenas** [icymind/VRouter#42]
### VRouter 版本
[0.4.0-beta.2](https://github.com/icymind/VRouter/tree/v0.4.0-beta.2)

### 操作系统版本
macOS 10.12.6

### VRouter 应用内, "系统"标签页的信息

系统信息

当前网关: 
当前 DNS: 
VRouter 信息

WAN: 
BR-LAN: 
Bridged Network: 
Mac Address: 
Openwrt Version: 
Shadowsocks Version: 
ShadowsocksR Version: 
Kcptun Version: 

### 暂停 VRouter 后, 以下命令(可一起执行)的执行结果
- macOS: nslookup qq.com;/sbin/route -n get default;tail -n 50 ~/Library/Application\ Support/vrouter/vrouter.log
```
Server:		202.120.190.208
Address:	202.120.190.208#53

Non-authoritative answer:
Name:	qq.com
Address: 14.17.32.211

   route to: default
destination: default
       mask: default
    gateway: 10.11.101.254
  interface: en0
      flags: <UP,GATEWAY,DONE,STATIC,PRCLONING>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0 
2017-09-08T14:00:24+08:00 - debug: about to trafficToPhysicalRouter
2017-09-08T14:00:24+08:00 - info: ssh connection has been ended
2017-09-08T14:00:24+08:00 - info: ssh connection was closed
2017-09-08T14:00:55+08:00 - info: no vrouter vm detected
2017-09-08T14:00:57+08:00 - info: building vm
2017-09-08T14:01:27+08:00 - error: build error: Error: getaddrinfo ENOTFOUND mirrors.tuna.tsinghua.edu.cn mirrors.tuna.tsinghua.edu.cn:443
2017-09-08T14:08:21+08:00 - info: building vm
2017-09-08T14:08:21+08:00 - error: build error: Error: Command failed: /usr/local/bin/VBoxManage controlvm vrouter poweroff
VBoxManage: error: Machine 'vrouter' is not currently running

2017-09-08T14:08:27+08:00 - info: building vm
2017-09-08T14:08:28+08:00 - error: build error: Error: Command failed: /usr/local/bin/VBoxManage controlvm vrouter poweroff
VBoxManage: error: Machine 'vrouter' is not currently running

2017-09-08T14:08:29+08:00 - info: building vm
2017-09-08T14:08:29+08:00 - error: build error: Error: Command failed: /usr/local/bin/VBoxManage controlvm vrouter poweroff
VBoxManage: error: Machine 'vrouter' is not currently running

2017-09-09T14:47:59+08:00 - info: vrouter vm not running
2017-09-09T14:48:30+08:00 - debug: vm started
2017-09-09T14:48:30+08:00 - debug: about to connect to openwrt via ssh
2017-09-09T14:48:31+08:00 - info: bridgeServices: en0: Wi-Fi (AirPort),en1: Thunderbolt 1,bridge0,p2p0,awdl0
2017-09-09T14:48:31+08:00 - info: actived Bridge Service: en0: Wi-Fi (AirPort)
2017-09-09T14:48:40+08:00 - warn: connecting to openwrt error: Timed out while waiting for handshake
2017-09-09T14:48:40+08:00 - info: ssh connection was closed
2017-09-09T14:49:29+08:00 - debug: about to connect to openwrt via ssh
2017-09-09T14:49:29+08:00 - info: bridgeServices: en0: Wi-Fi (AirPort),en1: Thunderbolt 1,bridge0,p2p0,awdl0
2017-09-09T14:49:29+08:00 - info: actived Bridge Service: en0: Wi-Fi (AirPort)
2017-09-09T14:49:40+08:00 - debug: about to connect to openwrt via ssh
2017-09-09T14:49:40+08:00 - info: bridgeServices: en0: Wi-Fi (AirPort),en1: Thunderbolt 1,bridge0,p2p0,awdl0
2017-09-09T14:49:40+08:00 - info: actived Bridge Service: en0: Wi-Fi (AirPort)
2017-09-09T14:49:50+08:00 - warn: connecting to openwrt error: Timed out while waiting for handshake
2017-09-09T14:49:50+08:00 - info: ssh connection was closed
2017-09-09T14:57:04+08:00 - info: vrouter vm not running
2017-09-09T14:57:35+08:00 - debug: vm started
2017-09-09T14:57:36+08:00 - debug: about to connect to openwrt via ssh
2017-09-09T14:57:36+08:00 - info: bridgeServices: en0: Wi-Fi (AirPort),en1: Thunderbolt 1,bridge0,p2p0,awdl0
2017-09-09T14:57:36+08:00 - info: actived Bridge Service: en0: Wi-Fi (AirPort)
2017-09-09T14:57:46+08:00 - warn: connecting to openwrt error: Timed out while waiting for handshake
2017-09-09T14:57:46+08:00 - info: ssh connection was closed
2017-09-09T15:06:26+08:00 - debug: about to connect to openwrt via ssh
2017-09-09T15:06:26+08:00 - info: bridgeServices: en0: Wi-Fi (AirPort),en1: Thunderbolt 1,bridge0,p2p0,awdl0
2017-09-09T15:06:26+08:00 - info: actived Bridge Service: en0: Wi-Fi (AirPort)
2017-09-09T15:06:36+08:00 - warn: connecting to openwrt error: Timed out while waiting for handshake
2017-09-09T15:06:36+08:00 - info: ssh connection was closed
2017-09-09T15:06:49+08:00 - debug: about to connect to openwrt via ssh
2017-09-09T15:06:49+08:00 - info: bridgeServices: en0: Wi-Fi (AirPort),en1: Thunderbolt 1,bridge0,p2p0,awdl0
2017-09-09T15:06:49+08:00 - info: actived Bridge Service: en0: Wi-Fi (AirPort)
2017-09-09T15:06:59+08:00 - warn: connecting to openwrt error: Timed out while waiting for handshake
2017-09-09T15:06:59+08:00 - info: ssh connection was closed
```

### 启用 VRouter 后, 以下命令(可一起执行)的执行结果
- macOS: nslookup qq.com;/sbin/route -n get default;tail -n 50 ~/Library/Application\ Support/vrouter/vrouter.log

无法启动，详见附件。

###错误详细信息
####在安装过程中报错

![2017-09-08 1 12 36](https://user-images.githubusercontent.com/26927236/30238035-6b9c30e6-9571-11e7-914c-621968aa08f0.png)
```
构建错误
Error: 未能安装必要软件包
    at t. (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:130214)
    at n (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:424655)
    at Generator._invoke (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:425774)
    at Generator.e.(anonymous function) [as next] (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:424834)
    at n (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:10320)
    at file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:10422
    at 
```
![2017-09-08 1 16 22](https://user-images.githubusercontent.com/26927236/30238042-85c66aa4-9571-11e7-9cf7-4ed4c91393c6.png)
![2017-09-08 2 08 16](https://user-images.githubusercontent.com/26927236/30238044-88c520ce-9571-11e7-9ba0-df50478fa4f1.png)
```
check virualbox installation
构建错误
Error: getaddrinfo ENOTFOUND mirrors.tuna.tsinghua.edu.cn mirrors.tuna.tsinghua.edu.cn:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```
![2017-09-08 2 08 26](https://user-images.githubusercontent.com/26927236/30238047-9baa5f10-9571-11e7-9277-36f0b458411b.png)
```
check virualbox installation
构建错误
Error: Command failed: /usr/local/bin/VBoxManage controlvm vrouter poweroff
VBoxManage: error: Machine 'vrouter' is not currently running

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket. (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

####尝试删除并重新安装，再次启动报错
![2017-09-09 2 48 38](https://user-images.githubusercontent.com/26927236/30238051-ac24bd4a-9571-11e7-9d6e-37e598cf454c.png)
```
Error: Cannot read property '1' of null
TypeError: Cannot read property '1' of null
    at Function.<anonymous> (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:116477)
    at n (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:424655)
    at Generator._invoke (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:425774)
    at Generator.e.(anonymous function) [as next] (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:424834)
    at n (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:10320)
    at file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:10422
    at <anonymous>
```

现在系统–删除也会报错`Error: Cannot read property '1' of null`，电脑的 DNS 未能恢复成以前的。

**Comment by icymind** [comment]
Error: getaddrinfo ENOTFOUND mirrors.tuna.tsinghua.edu.cn mirrors.tuna.tsinghua.edu.cn:443
    at errnoException (dns.js:28:10)

这条错误表明vrouter没能联网，请确保上游路由器开启了dhcp。
手动恢复网关和dns，请看wiki
https://github.com/icymind/VRouter/wiki/手动恢复网关

**Comment by Maecenas** [comment]
我按 wiki 的操作进行了手动恢复网关和 dns，在 Virtual Box 里面删除了原来的虚拟机并重新安装成功了，使用原来的配置还是不能使用，但是换了一个 ss 账号就行。是因为我使用了一些不兼容的协议吗？可以列出ssr支持的加密方法、协议和混淆吗？

SSR：
Encrypt Method: chacha20
Protocol: auth_chain_a
Obfs: tls1.2_ticket_auth

**Comment by icymind** [comment]
ssr 的二进制文件来自 https://github.com/ywb94/openwrt-ssr

项目的 README 指向的文档链接已经失效, 它支持哪种加密方法/混淆/协议无从得知, 抱歉了.

但是从项目的 issue 看, 它并不支持较新的Protocol: auth_chain_a

**Comment by icymind** [comment]
只能看他的源码了:
```lua
local encrypt_methods = {
	"table",
	"rc4",
	"rc4-md5",
	"rc4-md5-6",
	"aes-128-cfb",
	"aes-192-cfb",
	"aes-256-cfb",
	"aes-128-ctr",
	"aes-192-ctr",
	"aes-256-ctr",	
	"bf-cfb",
	"camellia-128-cfb",
	"camellia-192-cfb",
	"camellia-256-cfb",
	"cast5-cfb",
	"des-cfb",
	"idea-cfb",
	"rc2-cfb",
	"seed-cfb",
	"salsa20",
	"chacha20",
	"chacha20-ietf",
}

local protocol = {
	"origin",
	"verify_simple",
	"verify_sha1",		
	"auth_sha1",
	"auth_sha1_v2",
	"auth_sha1_v4",
	"auth_aes128_sha1",
	"auth_aes128_md5",
}

obfs = {
	"plain",
	"http_simple",
	"http_post",
	"tls_simple",	
	"tls1.2_ticket_auth",
}
```
