### ISSUE TITLE
未能安装必要软件包

### ISSUE THREAD

**Issue by xfoxfu** [icymind/VRouter#60]
```
Error: 未能安装必要软件包
    at t. (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:130293)
    at n (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:426205)
    at Generator._invoke (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:427324)
    at Generator.e.(anonymous function) [as next] (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:426384)
    at n (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:10229)
    at file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:10331
    at 
```

ssh 进入以后，发现软件源未被修改，tuna 源和 openwrt 源都可以连接上。

### VRouter 版本

0.4.1

### 操作系统版本

10.13 (17A405)

### 暂停 VRouter 后, 以下命令(可一起执行)的执行结果

```shell
$ nslookup qq.com;/sbin/route -n get default;tail -n 50 ~/Library/Application\ Support/vrouter/vrouter.log
Server:		192.168.199.1
Address:	192.168.199.1#53

Non-authoritative answer:
Name:	qq.com
Address: 14.17.32.211

   route to: default
destination: default
       mask: default
    gateway: 192.168.199.1
  interface: en0
      flags: <UP,GATEWAY,DONE,STATIC,PRCLONING>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0 
2017-10-20T13:29:09+08:00 - info: building vm
2017-10-20T13:29:10+08:00 - error: build error: Error: Command failed: /usr/local/bin/VBoxManage controlvm vrouter poweroff
VBoxManage: error: Machine 'vrouter' is not currently running

2017-10-20T13:29:23+08:00 - info: no vrouter vm detected
2017-10-20T13:29:27+08:00 - info: building vm
2017-10-20T13:29:27+08:00 - info: checking-for-update
2017-10-20T13:29:28+08:00 - info: hostonlyInf: vboxnet0
2017-10-20T13:29:28+08:00 - info: bridgeServices: en0: Wi-Fi (AirPort),en1: Thunderbolt 1,en2: Thunderbolt 2,p2p0,awdl0,bridge0
2017-10-20T13:29:28+08:00 - info: actived Bridge Service: en0: Wi-Fi (AirPort)
2017-10-20T13:29:31+08:00 - info: no update available
2017-10-20T13:30:00+08:00 - debug: about to run command: "uci set network.lan.ipaddr='10.19.28.37' && uci set network.lan.ipv6='0' && uci commit network && /etc/init.d/network restart" via serialTcpPort.
2017-10-20T13:30:00+08:00 - debug: wait output for 5000 ms
2017-10-20T13:30:09+08:00 - debug: netcat connection didn't close. resolve promise manually
2017-10-20T13:30:09+08:00 - debug: command: "uci set network.lan.ipaddr='10.19.28.37' && uci set network.lan.ipv6='0' && uci commit network && /etc/init.d/network restart"'s output: 000000000FFF0240 0001CC (v01 VBOX   VBOXCPUT 00000002 INTL 00000528)
2017-10-20T13:30:12+08:00 - debug: close netcat connection
2017-10-20T13:30:12+08:00 - debug: command: "uci set network.lan.ipaddr='10.19.28.37' && uci set network.lan.ipv6='0' && uci commit network && /etc/init.d/network restart"'s output: 000000000FFF0240 0001CC (v01 VBOX   VBOXCPUT 00000002 INTL 00000528)
2017-10-20T13:30:15+08:00 - debug: about to run command: "echo -e 'root\nroot' | (passwd root)" via serialTcpPort.
2017-10-20T13:30:15+08:00 - debug: wait output for 3000 ms
2017-10-20T13:30:19+08:00 - debug: close netcat connection
2017-10-20T13:30:19+08:00 - debug: command: "echo -e 'root\nroot' | (passwd root)"'s output: [ 078] Guest personality initialized and is inactive
2017-10-20T13:30:19+08:00 - debug: about to run command: "sed -i 's/downloads.openwrt.org/mirrors.tuna.tsinghua.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf && opkg update && opkg remove dnsmasq && opkg install dnsmasq-full ipset openssh-sftp-server libopenssl rng-tools iptables-mod-tproxy ip && /etc/init.d/dropbear restart && echo "done" > /tmp/log/vrouter" via serialTcpPort.
2017-10-20T13:30:19+08:00 - debug: wait output for 20000 ms
2017-10-20T13:30:41+08:00 - debug: close netcat connection
2017-10-20T13:30:41+08:00 - debug: command: "sed -i 's/downloads.openwrt.org/mirrors.tuna.tsinghua.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf && opkg update && opkg remove dnsmasq && opkg install dnsmasq-full ipset openssh-sftp-server libopenssl rng-tools iptables-mod-tproxy ip && /etc/init.d/dropbear restart && echo "done" > /tmp/log/vrouter"'s output: ed for UDMA/133
2017-10-20T13:30:41+08:00 - debug: check isInstallPackageFinish, time: 0
2017-10-20T13:30:41+08:00 - debug: about to connect to openwrt via ssh
2017-10-20T13:30:55+08:00 - warn: connecting to openwrt error: Timed out while waiting for handshake
2017-10-20T13:30:55+08:00 - warn: check isInstallPackageFinish failed, time: 0
2017-10-20T13:30:55+08:00 - debug: wait for 10000 ms to retry checking isInstallPackageFinish
2017-10-20T13:30:55+08:00 - info: ssh connection was closed
2017-10-20T13:31:05+08:00 - debug: check isInstallPackageFinish, time: 1
2017-10-20T13:31:05+08:00 - debug: about to connect to openwrt via ssh
2017-10-20T13:31:05+08:00 - warn: connecting to openwrt error: connect EHOSTDOWN 10.19.28.37:22 - Local (10.19.28.46:51198)
2017-10-20T13:31:05+08:00 - warn: check isInstallPackageFinish failed, time: 1
2017-10-20T13:31:05+08:00 - debug: wait for 10000 ms to retry checking isInstallPackageFinish
2017-10-20T13:31:05+08:00 - info: ssh connection was closed
2017-10-20T13:31:20+08:00 - debug: check isInstallPackageFinish, time: 2
2017-10-20T13:31:20+08:00 - debug: about to connect to openwrt via ssh
2017-10-20T13:31:30+08:00 - warn: connecting to openwrt error: Timed out while waiting for handshake
2017-10-20T13:31:30+08:00 - warn: check isInstallPackageFinish failed, time: 2
2017-10-20T13:31:30+08:00 - debug: wait for 10000 ms to retry checking isInstallPackageFinish
2017-10-20T13:31:30+08:00 - info: ssh connection was closed
2017-10-20T13:31:43+08:00 - debug: check isInstallPackageFinish, time: 3
2017^[[2;1;1;112;112;1;0x-10-20T13:31:43+08:00 - debug: about to connect to openwrt via ssh
2017-10-20T13:31:43+08:00 - warn: connecting to openwrt error: connect EHOSTDOWN 10.19.28.37:22 - Local (10.19.28.46:51202)
2017-10-20T13:31:43+08:00 - warn: check isInstallPackageFinish failed, time: 3
2017-10-20T13:31:43+08:00 - debug: wait for 10000 ms to retry checking isInstallPackageFinish
2017-10-20T13:31:43+08:00 - info: ssh connection was closed
2017-10-20T13:31:58+08:00 - error: build error: Error: 未能安装必要软件包
^[[2;1;1;112;112;1;0x%
```

**Comment by Error996** [comment]
+1 同样的错误

**Comment by lanx-x** [comment]
错误定位在
```shell
2017-10-20T13:30:41+08:00 - debug: command: "sed -i 's/downloads.openwrt.org/mirrors.tuna.tsinghua.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf && opkg update && opkg remove dnsmasq && opkg install dnsmasq-full ipset openssh-sftp-server libopenssl rng-tools iptables-mod-tproxy ip && /etc/init.d/dropbear restart && echo "done" > /tmp/log/vrouter"'s output: ed for UDMA/133
```
大概是virtualbox 虚拟磁盘的错误，但是我没能复现这个 bug（macOS 10.13 + virtualbox  5.1.28)。请尝试：
1. 删除 vrouter 虚拟机后重试；
2. 仍然不行的话请更新 virtualbox

**Comment by Felix2yu** [comment]
同样是构建错误
macOS 10.13.2 VirtualBox 5.2.0
尝试过删除虚机，Virtualbox 也是最新版。

```
nslookup qq.com;/sbin/route -n get default;tail -n 50 ~/Library/Application\ Support/vrouter/vrouter.log
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
Name:	qq.com
Address: 14.17.32.211

   route to: default
destination: default
       mask: default
    gateway: 192.168.1.1
  interface: en0
      flags: <UP,GATEWAY,DONE,STATIC,PRCLONING>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0
2017-11-03T21:44:24+08:00 - info: no vrouter vm detected
2017-11-03T21:44:27+08:00 - info: building vm
2017-11-03T21:44:28+08:00 - info: hostonlyInf: vboxnet0
2017-11-03T21:44:28+08:00 - info: checking-for-update
2017-11-03T21:44:28+08:00 - info: bridgeServices: en0: 以太网,en2: 雷雳 1,en3: 雷雳 2,en1: Wi-Fi (AirPort),p2p0,awdl0,bridge0,vmnet1,vmnet2,vmnet3,vmnet4,vmnet5,vmnet6,vmnet7,vmnet8,vmnet9,vmnet10,vmnet11,vmnet12,vmnet13,vmnet14,vmnet15,vmnet16,vmnet17,vmnet18,vmnet19,vmnet20,vmnet21,vmnet22,vmnet23,vmnet24,vmnet25,vmnet26,vmnet27,vmnet28,vmnet29,vmnet30,vmnet31,vmnet32,vmnet33,vmnet34,vmnet35,vmnet36,vmnet37,vmnet38,vmnet39,vmnet40,vmnet41,vmnet42,vmnet43,vmnet44,vmnet45,vmnet46,vmnet47,vmnet48,vmnet49,vmnet50,vmnet51,vmnet52,vmnet53,vmnet54,vmnet55,vmnet56,vmnet57,vmnet58,vmnet59,vmnet60,vmnet61,vmnet62,vmnet63,vmnet64,vmnet65,vmnet66,vmnet67,vmnet68,vmnet69,vmnet70,vmnet71,vmnet72,vmnet73,vmnet74,vmnet75,vmnet76,vmnet77,vmnet78,vmnet79,vmnet80,vmnet81,vmnet82,vmnet83,vmnet84,vmnet85,vmnet86,vmnet87,vmnet88,vmnet89,vmnet90,vmnet91,vmnet92,vmnet93,vmnet94,vmnet95,vmnet96,vmnet97,vmnet98,vmnet99,vmnet100,en6: iPhone USB
2017-11-03T21:44:28+08:00 - info: actived Bridge Service: en0: 以太网
2017-11-03T21:44:33+08:00 - info: no update available
2017-11-03T21:45:00+08:00 - debug: about to run command: "uci set network.lan.ipaddr='10.19.28.37' && uci set network.lan.ipv6='0' && uci commit network && /etc/init.d/network restart" via serialTcpPort.
2017-11-03T21:45:00+08:00 - debug: wait output for 5000 ms
2017-11-03T21:45:05+08:00 - debug: close netcat connection
2017-11-03T21:45:05+08:00 - debug: command: "uci set network.lan.ipaddr='10.19.28.37' && uci set network.lan.ipv6='0' && uci commit network && /etc/init.d/network restart"'s output:  msr 0:ffef001, primary cpu clock
2017-11-03T21:45:10+08:00 - debug: about to run command: "echo -e 'root\nroot' | (passwd root)" via serialTcpPort.
2017-11-03T21:45:10+08:00 - debug: wait output for 3000 ms
2017-11-03T21:45:13+08:00 - debug: close netcat connection
2017-11-03T21:45:13+08:00 - debug: command: "echo -e 'root\nroot' | (passwd root)"'s output: (SPd�������������@�����������L��[q��
2017-11-03T21:45:13+08:00 - debug: about to run command: "sed -i 's/downloads.openwrt.org/mirrors.tuna.tsinghua.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf && opkg update && opkg remove dnsmasq && opkg install dnsmasq-full ipset openssh-sftp-server libopenssl rng-tools iptables-mod-tproxy ip && /etc/init.d/dropbear restart && echo "done" > /tmp/log/vrouter" via serialTcpPort.
2017-11-03T21:45:13+08:00 - debug: wait output for 20000 ms
2017-11-03T21:45:33+08:00 - debug: close netcat connection
2017-11-03T21:45:33+08:00 - debug: command: "sed -i 's/downloads.openwrt.org/mirrors.tuna.tsinghua.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf && opkg update && opkg remove dnsmasq && opkg install dnsmasq-full ipset openssh-sftp-server libopenssl rng-tools iptables-mod-tproxy ip && /etc/init.d/dropbear restart && echo "done" > /tmp/log/vrouter"'s output:
2017-11-03T21:45:33+08:00 - debug: check isInstallPackageFinish, time: 0
2017-11-03T21:45:33+08:00 - debug: about to connect to openwrt via ssh
2017-11-03T21:45:43+08:00 - warn: connecting to openwrt error: Timed out while waiting for handshake
2017-11-03T21:45:43+08:00 - warn: check isInstallPackageFinish failed, time: 0
2017-11-03T21:45:43+08:00 - debug: wait for 10000 ms to retry checking isInstallPackageFinish
2017-11-03T21:45:43+08:00 - info: ssh connection was closed
2017-11-03T21:45:53+08:00 - debug: check isInstallPackageFinish, time: 1
2017-11-03T21:45:53+08:00 - debug: about to connect to openwrt via ssh
2017-11-03T21:45:53+08:00 - warn: connecting to openwrt error: connect EHOSTDOWN 10.19.28.37:22 - Local (10.19.28.46:53194)
2017-11-03T21:45:53+08:00 - warn: check isInstallPackageFinish failed, time: 1
2017-11-03T21:45:53+08:00 - debug: wait for 10000 ms to retry checking isInstallPackageFinish
2017-11-03T21:45:53+08:00 - info: ssh connection was closed
2017-11-03T21:46:03+08:00 - debug: check isInstallPackageFinish, time: 2
2017-11-03T21:46:03+08:00 - debug: about to connect to openwrt via ssh
2017-11-03T21:46:13+08:00 - warn: connecting to openwrt error: Timed out while waiting for handshake
2017-11-03T21:46:13+08:00 - warn: check isInstallPackageFinish failed, time: 2
2017-11-03T21:46:13+08:00 - debug: wait for 10000 ms to retry checking isInstallPackageFinish
2017-11-03T21:46:13+08:00 - info: ssh connection was closed
2017-11-03T21:46:23+08:00 - debug: check isInstallPackageFinish, time: 3
2017-11-03T21:46:23+08:00 - debug: about to connect to openwrt via ssh
2017-11-03T21:46:23+08:00 - warn: connecting to openwrt error: connect EHOSTDOWN 10.19.28.37:22 - Local (10.19.28.46:53203)
2017-11-03T21:46:23+08:00 - warn: check isInstallPackageFinish failed, time: 3
2017-11-03T21:46:23+08:00 - debug: wait for 10000 ms to retry checking isInstallPackageFinish
2017-11-03T21:46:23+08:00 - info: ssh connection was closed
2017-11-03T21:46:33+08:00 - error: build error: Error: 未能安装必要软件包
```

**Comment by xfoxfu** [comment]
我和@Felix2yu 的版本是一致的，尝试的操作步骤也是一致的。

**Comment by lanx-x** [comment]
```
sed -i 's/downloads.openwrt.org/mirrors.tuna.tsinghua.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf

opkg update

opkg remove dnsmasq

opkg install dnsmasq-full ipset openssh-sftp-server libopenssl rng-tools iptables-mod-tproxy ip 

/etc/init.d/dropbear restart

echo "done" > /tmp/log/vrouter"
```
hi, 能否麻烦你们在出现“未能安装必要软件包”的错误时，登入虚拟机，依次执行以上命令，看看具体是哪条命令出了错

**Comment by Error996** [comment]
我单个执行没问题，最后一条命令你多了个双引号吧最后

**Comment by etnperlong** [comment]
+1，同样的问题，按照@icymind的方法单个执行，安装有conffiles文件冲突。
指向/etc/config/dhcp

**Comment by puteulanus** [comment]
同样的问题，VRouter 版本 0.4.2，操作系统 10.10.5。VirtualBox 已更新到最新版。

<img width="1178" alt="default" src="https://user-images.githubusercontent.com/4849177/33251043-9b9148a4-d36f-11e7-8451-2b14d14e27d4.png">

配置软件源的时候进虚拟机是这样的，看起来依然还在启动中，是因为等待系统启动的时间不够长吗？已经尝试过把 CPU 分配到 4 线程了，但似乎启动过程中总会在几个位置卡比较长的时间。

**Comment by yangyuw** [comment]
@icymind +1，同样的问题，按照@icymind的方法单个执行，安装有conffiles文件冲突。
指向/etc/config/dhcp
vroute 0.4.2
virtualbox 6.0.2
macos 10.14.5
