### ISSUE TITLE
切换网络后本地IP无法自动更换

### ISSUE THREAD

**Issue by LomotHo** [icymind/VRouter#66]
比如我的WAN 的IP本来是192.168.1.100
然后我换了路由器，电脑的ifconfig中显示的本地ip已经换成了192.168.31.240
但是vrouter的中的IP没有自动切换，在vrouter0.3.2b中有个刷新本地IP的按钮，这个版本没找到

### VRouter 版本
0.4.2
### 操作系统版本
MacOS10.13.1
### VRouter 应用内, "系统"标签页的信息
WAN: 192.168.31.240
BR-LAN: 10.19.28.37
Bridged Network: en0: Wi-Fi (AirPort)
Mac Address: 08:00:27:39:79:a6
Openwrt Version: 15.05.1
Shadowsocks Version: 3.1.0
ShadowsocksR Version: 2.5.6
Kcptun Version: 20170904

**Comment by lanx-x** [comment]
因为之前有测试过，切换物理路由器后虚拟机也能自动切换 ip，所以就把刷新按钮去掉了。能否请你帮忙测试下，是切换延迟还是无法自动切换到192.168.31.x？等10分钟就好

**Comment by LomotHo** [comment]
测试结果
切换wifi几秒钟后ping开始超时
vrouter的系统标签页的ip没有切换，点击右下角刷新无效
5分钟后状态没有变化
点击状态标签页的暂停后，ping连通，重新点击启用后ping继续超时
重启vrouter（恢复虚拟机，不是重启）后ip改变，ping连通

重启vrouter过程中碰到另一个不可重现bug，一共出现过两次
Error: Command failed: /usr/local/bin/VBoxManage startvm --type headless vrouter
VBoxManage: error: Failed to load unit 'HGCM' (VERR_SSM_UNEXPECTED_DATA)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by lanx-x** [comment]
谢谢反馈，我会在后续版本中把刷新 ip 的按钮重新加上
