### ISSUE TITLE
构建错误

### ISSUE THREAD

**Issue by maxming2333** [icymind/VRouter#67]
### VRouter 版本

v0.4.2

### 操作系统版本

macos sierra 10.12.6

### 错误详情

```
构建错误
Error: 未能安装必要软件包
    at t. (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:133657)
    at n (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:430391)
    at Generator._invoke (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:431510)
    at Generator.e.(anonymous function) [as next] (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:430570)
    at n (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:10303)
    at file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:10405
    at 
```

**Comment by maxming2333** [comment]
安装的时候出错
