### ISSUE TITLE
 Vrouter 在 VirtualBox 5.2.2 版本下 无法 正常使用，会提示 未能安装必要软件包 

### ISSUE THREAD

**Issue by ciskonc** [icymind/VRouter#69]
### VRouter 版本
0.4.1
### 操作系统版本
windows

Vrouter 在 VirtualBox 5.2.2 版本下 无法 正常使用，会提示 未能安装必要软件包 
然后我在VirtualBox 5.0版本下 正常使用。

**Comment by rosuH** [comment]
Win10 同样情况。
VirtualBox 回退到 5.1 解决问题。
记得在删除原来的虚拟文件。

https://github.com/icymind/VRouter/issues/39

**Comment by coolicer** [comment]
@rosuH 哪个版本能用，我用5.1.28还是不行

**Comment by rosuH** [comment]
@coolicer 当时下载的应该是 [5.1.30](https://www.virtualbox.org/wiki/Download_Old_Builds_5_1)。
当你把上一个版本卸载之后，最好删掉遗留的文件。参看上面我的引用  #39 .

**Comment by coolicer** [comment]
@rosuH 我在vrouter点了删除，我的是mac

**Comment by rosuH** [comment]
@coolicer 噢...那得自己看看目录文件位置了。或许可以使用`find`命令代为查询。
如果 Mac 有的话。

**Comment by gilbertwong96** [comment]
该问题还未解决吗？

**Comment by qiwihui** [comment]
The same problem occurs to VirtualBox 5.2.x on macOS:

VRouter version：0.4.1
os system：macOS High Sierra 10.13.6
VirtualBox version: `5.2.16 r123759`

Error:
```js
构建错误
Error: 未能安装必要软件包
    at t. (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:133657)
    at n (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:430391)
    at Generator._invoke (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:431510)
    at Generator.e.(anonymous function) [as next] (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:430570)
    at n (file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:10303)
    at file:///Applications/VRouter.app/Contents/Resources/app.asar/dist/electron/renderer.bundle.js:1:10405
    at 
```

Solution:

After I downgrade VirtualBox to version `5.1.38 r122592`, it works.

**Comment by louchenyao** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by yangyuw** [comment]
升级到macOS 10.14以后就不能回退到 virtualBox 5.1 了， 这个问题难搞哦，作者难道没用了吗
