### ISSUE TITLE
出现错误,请问有办法解决么

### ISSUE THREAD

**Issue by yume233** [icymind/VRouter#77]
Error: Command failed: "E:\Program Files\Oracle\VirtualBox\VBoxManage.exe" startvm --type headless vrouter
VBoxManage.exe: error: DrvTCP#0 failed to create server socket (VERR_UNRESOLVED_ERROR)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

请问出现这样的报错是为什么~有解决的方法么~

**Comment by yume233** [comment]
0.0是VirtualBox版本的原因~打扰了

**Comment by yume233** [comment]
Error: 未能安装必要软件包
    at t. (file:///C:/Users/xxxxx/AppData/Local/Programs/VRouter/resources/app.asar/dist/electron/renderer.bundle.js:1:130293)
    at n (file:///C:/Users/xxxxx/AppData/Local/Programs/VRouter/resources/app.asar/dist/electron/renderer.bundle.js:1:426205)
    at Generator._invoke (file:///C:/Users/xxxxx/AppData/Local/Programs/VRouter/resources/app.asar/dist/electron/renderer.bundle.js:1:427324)
    at Generator.e.(anonymous function) [as next] (file:///C:/Users/xxxxx/AppData/Local/Programs/VRouter/resources/app.asar/dist/electron/renderer.bundle.js:1:426384)
    at n (file:///C:/Users/xxxxx/AppData/Local/Programs/VRouter/resources/app.asar/dist/electron/renderer.bundle.js:1:10229)
    at file:///C:/Users/xxxxx/AppData/Local/Programs/VRouter/resources/app.asar/dist/electron/renderer.bundle.js:1:10331
    at 



= =然后还是有错误~

**Comment by crysislinux** [comment]
我debug了一下，我这儿出现这个的原因是Openwrt因为某种原因启动的非常慢。Vrouter里只是等待了30s，本来时间是够的，但是因为这个未知原因，Openwrt花了5分钟才完全启动，结果就是后面的命令全部失败了。奇怪的是我另外一个直接装的Openwrt又启动很快。。

**Comment by crysislinux** [comment]
不过只要第一次设置完成了。之后就正常了，我的办法是:

1. clone 项目代码
2. npm install
3. 修改 VRouter/src/renderer/lib/vrouter.js L130  ```await Utils.wait(30000)``` 改成 ```await Utils.wait(5 * 60 * 1000)```，直接等它5分钟。
4. npm run dev
5. 构建虚拟机，这次应该能成功

完了之后关闭推出这个开发版，现在打开production的版本，就会发现之前的虚拟机，不用重新构建了。

**Comment by StephenEX** [comment]
我也碰到这个问题。我发现好像是文件解压出了问题。用楼上办法解决不了的话可以试试安装Node.js，我是手动解压好再继续运行的，不知道装好Node.js之后能不能自动解压成功。

**Comment by hootigger** [comment]
我mac 10.13.4也遇到了这个问题,按照@crysislinux 说的操作,可以完成,vbox版本5.2.14最新,但是在npm阶段错误很多,报有个依赖404,删除node_modules,在packege.json中修改"electron-updater的版本为2.18.2,然后用淘宝的cnpm install & cnpm run dev解决了,下载软件错误的提示.
