### ISSUE TITLE
0.4.2 版本启动失败

### ISSUE THREAD

**Issue by tongjieme** [icymind/VRouter#78]
### VRouter 版本
0.4.2
### 操作系统版本
Mac Sierra 10.12.6
### VRouter 应用内, "系统"标签页的信息
(启动失败, 无法提供)
### 暂停 VRouter 后, 以下命令(可一起执行)的执行结果
- macOS: nslookup qq.com;/sbin/route -n get default;tail -n 50 ~/Library/Application\ Support/vrouter/vrouter.log
```
 nslookup qq.com;/sbin/route -n get default;tail -n 50 ~/Library/Application\ Support/vrouter/vrouter.log
Server:		114.114.114.114
Address:	114.114.114.114#53

Non-authoritative answer:
Name:	qq.com
Address: 14.17.32.211

   route to: default
destination: default
       mask: default
    gateway: 192.168.2.1
  interface: en0
      flags: <UP,GATEWAY,DONE,STATIC,PRCLONING>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0 
2018-03-19T15:54:35+08:00 - info: vrouter vm not running
2018-03-19T15:54:36+08:00 - error: fail to start vm
2018-03-19T15:54:38+08:00 - info: checking-for-update
2018-03-19T15:54:47+08:00 - info: no update available
2018-03-19T15:54:59+08:00 - error: fail to start vm
2018-03-19T15:55:25+08:00 - error: fail to start vm
2018-03-19T16:33:55+08:00 - info: about to quit VRouter
2018-03-19T16:33:55+08:00 - info: action off
2018-03-19T16:33:55+08:00 - debug: about to trafficToPhysicalRouter
2018-03-19T16:34:05+08:00 - error:  Error: Command failed: /usr/local/bin/VBoxManage controlvm vrouter savestate
VBoxManage: error: Machine 'vrouter' is not currently running

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
2018-03-19T16:37:12+08:00 - info: about to quit VRouter
2018-03-19T16:37:12+08:00 - info: action off
2018-03-19T16:37:13+08:00 - debug: about to trafficToPhysicalRouter
2018-03-19T16:37:20+08:00 - error:  Error: Command failed: /usr/local/bin/VBoxManage controlvm vrouter savestate
VBoxManage: error: Machine 'vrouter' is not currently running

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
2018-03-19T16:48:16+08:00 - info: vrouter vm not running
2018-03-19T16:48:17+08:00 - error: fail to start vm
2018-03-19T17:15:14+08:00 - error: fail to start vm
2018-03-19T17:15:14+08:00 - error: fail to start vm
2018-03-19T17:15:14+08:00 - error: fail to start vm
2018-03-21T09:18:17+08:00 - info: vrouter vm not running
2018-03-21T09:18:17+08:00 - error: fail to start vm
2018-03-21T09:18:19+08:00 - info: checking-for-update
2018-03-21T09:19:28+08:00 - info: vrouter vm not running
2018-03-21T09:19:29+08:00 - error: fail to start vm
2018-03-21T09:19:31+08:00 - info: checking-for-update
2018-03-21T09:19:37+08:00 - info: no update available
2018-03-21T09:27:11+08:00 - info: vrouter vm not running
2018-03-21T09:27:11+08:00 - error: fail to start vm
2018-03-21T09:27:13+08:00 - info: checking-for-update
2018-03-21T09:27:20+08:00 - info: no update available
```
### 启用 VRouter 后, 以下命令(可一起执行)的执行结果
- macOS: nslookup qq.com;/sbin/route -n get default;tail -n 50 ~/Library/Application\ Support/vrouter/vrouter.log
```
nslookup qq.com;/sbin/route -n get default;tail -n 50 ~/Library/Application\ Support/vrouter/vrouter.log
Server:		114.114.114.114
Address:	114.114.114.114#53

Non-authoritative answer:
Name:	qq.com
Address: 14.17.32.211

   route to: default
destination: default
       mask: default
    gateway: 192.168.2.1
  interface: en0
      flags: <UP,GATEWAY,DONE,STATIC,PRCLONING>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0 
2018-03-19T15:54:35+08:00 - info: vrouter vm not running
2018-03-19T15:54:36+08:00 - error: fail to start vm
2018-03-19T15:54:38+08:00 - info: checking-for-update
2018-03-19T15:54:47+08:00 - info: no update available
2018-03-19T15:54:59+08:00 - error: fail to start vm
2018-03-19T15:55:25+08:00 - error: fail to start vm
2018-03-19T16:33:55+08:00 - info: about to quit VRouter
2018-03-19T16:33:55+08:00 - info: action off
2018-03-19T16:33:55+08:00 - debug: about to trafficToPhysicalRouter
2018-03-19T16:34:05+08:00 - error:  Error: Command failed: /usr/local/bin/VBoxManage controlvm vrouter savestate
VBoxManage: error: Machine 'vrouter' is not currently running

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
2018-03-19T16:37:12+08:00 - info: about to quit VRouter
2018-03-19T16:37:12+08:00 - info: action off
2018-03-19T16:37:13+08:00 - debug: about to trafficToPhysicalRouter
2018-03-19T16:37:20+08:00 - error:  Error: Command failed: /usr/local/bin/VBoxManage controlvm vrouter savestate
VBoxManage: error: Machine 'vrouter' is not currently running

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
2018-03-19T16:48:16+08:00 - info: vrouter vm not running
2018-03-19T16:48:17+08:00 - error: fail to start vm
2018-03-19T17:15:14+08:00 - error: fail to start vm
2018-03-19T17:15:14+08:00 - error: fail to start vm
2018-03-19T17:15:14+08:00 - error: fail to start vm
2018-03-21T09:18:17+08:00 - info: vrouter vm not running
2018-03-21T09:18:17+08:00 - error: fail to start vm
2018-03-21T09:18:19+08:00 - info: checking-for-update
2018-03-21T09:19:28+08:00 - info: vrouter vm not running
2018-03-21T09:19:29+08:00 - error: fail to start vm
2018-03-21T09:19:31+08:00 - info: checking-for-update
2018-03-21T09:19:37+08:00 - info: no update available
2018-03-21T09:27:11+08:00 - info: vrouter vm not running
2018-03-21T09:27:11+08:00 - error: fail to start vm
2018-03-21T09:27:13+08:00 - info: checking-for-update
2018-03-21T09:27:20+08:00 - info: no update available
```

## 截图
![screen shot 2018-03-21 at 9 51 18 am](https://user-images.githubusercontent.com/1511418/37691524-8ee81f7e-2ced-11e8-9dc6-91727c6bff49.png)

**Comment by tongjieme** [comment]
自己找到问题了, Virtual Box 网卡设置问题
